language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="django==1.6.2"
  - DJANGO="django==1.5.5"
  - DJANGO="django==1.4.10"

# command to install dependencies
install:
  - pip install $DJANGO
  - export PYTHONPATH=.

script:
  - python unsubscribe/runtests/runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.10"
    - python: "3.3"
      env: DJANGO="django==1.4.10"
