language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.7"
  - DJANGO="django==1.6.7"
  - DJANGO="django==1.5.5"
  - DJANGO="django==1.4.10"

# command to install dependencies
install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - export PYTHONPATH=.

before_script:
  - flake8

script:
  - python unsubscribe/runtests/runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.10"
    - python: "3.3"
      env: DJANGO="django==1.4.10"
    - python: "3.4"
      env: DJANGO="django==1.4.10"
