language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
env:
- DJANGO="django==1.7"
- DJANGO="django==1.6.7"
- DJANGO="django==1.5.5"
- DJANGO="django==1.4.10"
install:
- pip install $DJANGO
- pip install -r requirements.txt
- export PYTHONPATH=.
before_script:
- flake8
script:
- python unsubscribe/runtests/runtests.py
matrix:
  exclude:
  - python: '3.2'
    env: DJANGO="django==1.4.10"
  - python: '3.3'
    env: DJANGO="django==1.4.10"
  - python: '3.4'
    env: DJANGO="django==1.4.10"
deploy:
  provider: pypi
  user: theskumar
  password:
    secure: HGOzjWP5mSqEEbnmNmSfiapGECPJwXfkuXZtdB7Ix9CW59IYuWw6LV7Rkm6SrmxfXxQV/HiAveUEIAqGV4ei5+txgoZC+ZgkpW+WVAl1W3m5MP7Gq6PTkP/YeIyUceKcgzUT62ifMAY6GkUriGQ8BtklKRoBNdIZwSM05AtpBzE=
  on:
    tags: true
    all_branches: true # https://github.com/travis-ci/travis-ci/issues/1675
